services:
  mynodeapp:
    container_name: test-app       # Friendly container name
    build:
      context: .                          # Uses Dockerfile in this folder
      dockerfile: Dockerfile
    image: mytestapp:v1.0                     # Name & version of image
    ports:
      - "3000:3000"                       # Map port 3000 (host) to 3000 (container)
    environment:
      - NODE_ENV=production
    restart: always                       # Auto-restart on failure/reboot
    deploy:
      resources:
        limits:
          cpus: '0.50'                    # Optional: CPU usage limit
          memory: 512M                    # Optional: Memory usage limit
