services:
  mynodeapp:
    container_name: ${CONTAINER_NAME}        # dynamic container name
    image: ${IMAGE_NAME}                     # dynamically built image name
    ports:
      - "${APP_PORT}:3000"                   # host:container port
    volumes:
      - "${VOLUME_NAME}:/app/data"           # persistent volume
    environment:
      - NODE_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  app-volume:
    name: ${VOLUME_NAME}